GET {{HOST}}/auth/me
###

GET {{HOST}}/_auth/session
###

POST {{HOST}}/auth/register
Content-Type: application/json
{
    "username": "username",
    "password": "password"
}
###

POST {{HOST}}/auth/login
Content-Type: application/json
{
    "username": "username",
    "password": "password"
}
###

POST {{HOST}}/auth/logout
###

GET {{HOST}}/users
###

GET {{HOST}}/desks?start=2024-12-19
###

POST {{HOST}}/desks
###

GET {{HOST}}/bookings
###

POST {{HOST}}/bookings
Content-Type: application/json
{
    "bookedDate": "2024-12-22",
    "deskId": "g9cf5vu8khgm4oeyjdyok5oa",
    "createdBy": "t289dn9g3mgzwgge9s79x9l7"
}

